/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import lab7.Huffman;

public class AppTest {
    @Test public void appHasAGreeting() {
        Huffman newHuffman = new Huffman();
        
    }
}
