/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import lab7.Huffman;

public class HuffmanTest {
    @Test public void appHasAGreeting() {
        System.out.println("works");
        
    }
}
