/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;


public class Huffman {

    class Letter {
	String letter;
	int freq;
	Letter next;

	public Letter(int
    }

    public static void main(String[] args) {
        String string = args;
	
    }
}
